name: AcceptRules
version: 1.6
main: me.rigi.acceptrules.AcceptRulesMain
permissions:
    acceptrules.settp:
        description: /acceptrules settp
        default: op
    acceptrules.notifyonaccept:
        description: sends message when someone accepts rules!
        default: false
commands:
  acceptrules:
    description: Used to accept rules!
    usage: /acceptrules
  rules:
    description: Used to read rules!
    usage: /rules